import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {cn} from '@/utils/cn'
import Image from 'next/image'
import backgroundImage from '../../public/background-dark.jpg'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn('relative text-slate-300 bg-[#0F111A] overflow-x-hidden', inter.className)}>
        <div className="absolute -inset-x-8 -top-8">
          <Image src={backgroundImage} alt="Background Image" className="w-full blur" />
        </div>
        <main>{children}</main>
      </body>
    </html>
  )
}
